name = raw_input('Name: ')
address_city = raw_input('City: ')
address_state = raw_input('State: ')
address_ZIP = raw_input('ZIP: ')
college_major = raw_input('College major: ')
print 'Name = ', name
print 'City = ', address_city
print 'State = ', address_state
print 'ZIP code = ', address_ZIP
print 'College Major = ', college_major
